apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-dispatcher
  name: notification-dispatcher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: notification-dispatcher
    spec:
      containers:
      - args:
        - ./dispatchers/notification_dispatcher
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: DEFAULT_FROM
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_FROM
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: DISPATCHER_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_DATABASE_URL
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: DISPATCHER_DB_CHANNEL
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_DB_CHANNEL
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: DISPATCHER_EXEC
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_EXEC
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: DISPATCHER_MODE
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_MODE
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: DISPATCHER_REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_REDIS_URL
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: DISPATCHER_WORKERS
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_WORKERS
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: SENDGRID_API_KEY
          valueFrom:
            configMapKeyRef:
              key: SENDGRID_API_KEY
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: SENTRY_DSN
              name: notification-dispatcher-compose_env--notification_dispatcher-env
        image: notification-dispatcher
        name: notification-dispatcher
        resources: {}
      restartPolicy: Always
status: {}
