apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-stream-processor
  name: payment-stream-processor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: payment-stream-processor
    spec:
      containers:
      - args:
        - ./dispatchers/payment_stream_processor
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: DISPATCHER_CHANNEL
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_CHANNEL
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: DISPATCHER_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_DATABASE_URL
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: DISPATCHER_EXEC
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_EXEC
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: DISPATCHER_MODE
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_MODE
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: DISPATCHER_REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_REDIS_URL
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: DISPATCHER_WORKERS
          valueFrom:
            configMapKeyRef:
              key: DISPATCHER_WORKERS
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: GATEWAY_API_KEY
          valueFrom:
            configMapKeyRef:
              key: GATEWAY_API_KEY
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: POSTBACK_URL
          valueFrom:
            configMapKeyRef:
              key: POSTBACK_URL
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: SENTRY_DSN
              name: payment-stream-processor-compose_env--payment_stream_processor-env
        image: payment-stream-processor
        name: payment-stream-processor
        resources: {}
      restartPolicy: Always
status: {}
