apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: recommender-service-api
  name: recommender-service-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: recommender-service-api
    spec:
      containers:
      - args:
        - gunicorn
        - -w
        - "4"
        - -b
        - 0.0.0.0:3009
        - catarse_recommender.application:app
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: recommender-service-api-compose_env--recommender_service_api-env
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              key: FLASK_APP
              name: recommender-service-api-compose_env--recommender_service_api-env
        - name: LANG
          valueFrom:
            configMapKeyRef:
              key: LANG
              name: recommender-service-api-compose_env--recommender_service_api-env
        - name: LC_ALL
          valueFrom:
            configMapKeyRef:
              key: LC_ALL
              name: recommender-service-api-compose_env--recommender_service_api-env
        - name: PYTHONPATH
          valueFrom:
            configMapKeyRef:
              key: PYTHONPATH
              name: recommender-service-api-compose_env--recommender_service_api-env
        image: recommender-service-api
        name: recommender-service-api
        ports:
        - containerPort: 3009
        resources: {}
      restartPolicy: Always
status: {}
