apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: catarse
  name: catarse
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "webpack-dev"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: catarse
status:
  loadBalancer: {}
