apiVersion: v1
data:
  DATABASE_URL: postgres://postgres:example@service-core-db:5432/service_core
  DISPATCHER_CHANNEL: payment_stream
  DISPATCHER_DATABASE_URL: postgres://postgres:example@service-core-db:5432/service_core
  DISPATCHER_EXEC: ./main.js
  DISPATCHER_MODE: both
  DISPATCHER_REDIS_URL: redis://dispatcher-redis:6379
  DISPATCHER_WORKERS: "2"
  GATEWAY_API_KEY: API_PAGARME_TEST_HERE
  POSTBACK_URL: URL_FOR_POSTBACK
  SENTRY_DSN: SENTRY_DSN_CONNECTION_URL
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: payment-stream-processor-env
  name: payment-stream-processor-env
