apiVersion: v1
data:
  DATABASE_URL: postgres://postgres:example@service-core-db:5432/service_core
  PGRST_DB_ANON_ROLE: anonymous
  PGRST_DB_POOL: "10"
  PGRST_DB_SCHEMA: payment_service_api
  PGRST_DB_URI: postgres://postgrest:example@service-core-db:5432/service_core
  PGRST_JWT_SECRET: bUH75katNm6Yj0iPSchcgUuTwYAzZr7C
  PGRST_SERVER_HOST: 0.0.0.0
  PGRST_SERVER_PORT: "3000"
  PGRST_SERVER_PROXY_URI: https://0.0.0.0:3000/
  POSTGREST_VER: 0.4.3.0
  PROCESS_PAYMENT_DATABASE_URL: postgres://postgres:example@service-core-db:5432/service_core
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: payment-service-api-env
  name: payment-service-api-env
