apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: service-core-db
  name: service-core-db
spec:
  ports:
  - port: 5432
  selector:
    io.kompose.service: service-core-db
status:
  loadBalancer: {}
