apiVersion: v1
data:
  DATABASE_URL: postgres://catarse:example@catarse-db:5432/catarse_db
  PGRST_DB_ANON_ROLE: anonymous
  PGRST_DB_POOL: "10"
  PGRST_DB_SCHEMA: "1"
  PGRST_DB_URI: postgres://catarse:example@catarse-db:5432/catarse_db
  PGRST_SERVER_HOST: 0.0.0.0
  PGRST_SERVER_PORT: "3000"
  PGRST_SERVER_PROXY_URI: https://0.0.0.0:3000/
  POSTGREST_VER: 0.4.3.0
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: catarse-api-compose-env
  name: catarse-api-compose-env
