apiVersion: v1
data:
  PGRST_DB_ANON_ROLE: anonymous
  PGRST_DB_POOL: "10"
  PGRST_DB_SCHEMA: read_service_api
  PGRST_SERVER_HOST: 0.0.0.0
  PGRST_SERVER_PORT: "3000"
  PGRST_SERVER_PROXY_URI: https://0.0.0.0:3000/
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: read-api-env
  name: read-api-env
